export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum UserRoles {
  ADMIN = 'ADMIN',
  ALUMNO = 'ALUMNO',
  PROFESOR = 'PROFESOR',
  VENDEDOR = 'VENDEDOR',
}

export enum TeacherStatus {
  NOT_REQUESTED = 'NOT_REQUESTED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
}
